<a href="https://colab.research.google.com/github/223t1a3105/colab-saved-data/blob/main/Deep_Learning_Lab_1(27_07_24).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


In [2]:
# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)


Vector values: [1 2 3]


LAB 1

In [3]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


PROGRAM TO PREDICT SUM OF TWO NUMBERS

In [7]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.2)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/5
100/100 [==============================] - 1s 3ms/step - loss: 9712.7842 - val_loss: 7086.8286
Epoch 2/5
100/100 [==============================] - 0s 2ms/step - loss: 3754.8523 - val_loss: 496.2448
Epoch 3/5
100/100 [==============================] - 0s 5ms/step - loss: 108.1862 - val_loss: 24.2409
Epoch 4/5
100/100 [==============================] - 1s 6ms/step - loss: 17.9462 - val_loss: 11.9151
Epoch 5/5
63/63 [==============================] - 0s 2ms/step - loss: 6.0846
Test Loss: 6.08463191986084
1/1 [==============================] - 0s 86ms/step
Predicted Sum: 66.96077728271484


In [10]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=6, batch_size=66, validation_split=0.3)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

# Make a prediction
sample_input = np.array([[23, 45]])  # Example input
predicted_sum = model.predict(sample_input)
print(f'Predicted Sum: {predicted_sum[0][0]}')


Epoch 1/6
85/85 [==============================] - 1s 4ms/step - loss: 9774.9590 - val_loss: 8321.9092
Epoch 2/6
85/85 [==============================] - 0s 2ms/step - loss: 6336.2588 - val_loss: 4011.7708
Epoch 3/6
85/85 [==============================] - 0s 3ms/step - loss: 2017.5802 - val_loss: 589.0287
Epoch 4/6
85/85 [==============================] - 0s 3ms/step - loss: 214.0988 - val_loss: 90.9243
Epoch 5/6
85/85 [==============================] - 0s 2ms/step - loss: 67.9855 - val_loss: 57.3463
Epoch 6/6
63/63 [==============================] - 0s 1ms/step - loss: 34.1011
Test Loss: 34.101112365722656
1/1 [==============================] - 0s 63ms/step
Predicted Sum: 64.56755828857422
